/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_DCB_FIRMWARE_LL_PROTOCOL_MESSAGE_PB_H_INCLUDED
#define PB_DCB_FIRMWARE_LL_PROTOCOL_MESSAGE_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _ThrustersState {
    ThrustersState_THRUSTERS_POWER_OFF = 0,
    ThrustersState_THRUSTERS_POWER_ON = 1,
    ThrustersState_THRUSTERS_NORMAL_OPERATION = 2,
    ThrustersState_THRUSTERS_STOP = 3
} ThrustersState;

/* Состояния работы модулей питания PAF */
typedef enum _PAF_Status {
    PAF_Status_PAF_NONE = 0,
    PAF_Status_PAF_OK = 1,
    PAF_Status_PAF_ERROR = 2
} PAF_Status;

/* Struct definitions */
typedef struct _LightingOnCommand {
    uint32_t channel;
    uint32_t brightness;
} LightingOnCommand;

typedef struct _ThrustersControl {
    ThrustersState state;
    uint32_t configuration; /* кофигурация ДРК */
    int32_t level[8]; /* int16 th1_speed = 2; // -100%..100%
int16 th2_speed = 3; // -100%..100%
int16 th3_speed = 4; // -100%..100%
int16 th4_speed = 5; // -100%..100%
int16 th5_speed = 6; // -100%..100%
int16 th6_speed = 7; // -100%..100%
int16 th7_speed = 8; // -100%..100%
int16 th8_speed = 9; // -100%..100% */
} ThrustersControl;

/* Данные монитора питания системы (напряжение и ток) */
typedef struct _Telemetry_PowerMonitor {
    float voltage; /* Напряжение */
    float current; /* Ток */
    PAF_Status paf_1;
    PAF_Status paf_2;
    PAF_Status paf_3;
    PAF_Status paf_4;
    PAF_Status paf_5;
} Telemetry_PowerMonitor;

typedef struct _Telemetry {
    uint32_t msg_id;
    bool has_power_monitor;
    Telemetry_PowerMonitor power_monitor;
} Telemetry;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ThrustersState_MIN ThrustersState_THRUSTERS_POWER_OFF
#define _ThrustersState_MAX ThrustersState_THRUSTERS_STOP
#define _ThrustersState_ARRAYSIZE ((ThrustersState)(ThrustersState_THRUSTERS_STOP+1))

#define _PAF_Status_MIN PAF_Status_PAF_NONE
#define _PAF_Status_MAX PAF_Status_PAF_ERROR
#define _PAF_Status_ARRAYSIZE ((PAF_Status)(PAF_Status_PAF_ERROR+1))


#define ThrustersControl_state_ENUMTYPE ThrustersState


#define Telemetry_PowerMonitor_paf_1_ENUMTYPE PAF_Status
#define Telemetry_PowerMonitor_paf_2_ENUMTYPE PAF_Status
#define Telemetry_PowerMonitor_paf_3_ENUMTYPE PAF_Status
#define Telemetry_PowerMonitor_paf_4_ENUMTYPE PAF_Status
#define Telemetry_PowerMonitor_paf_5_ENUMTYPE PAF_Status


/* Initializer values for message structs */
#define LightingOnCommand_init_default           {0, 0}
#define ThrustersControl_init_default            {_ThrustersState_MIN, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define Telemetry_init_default                   {0, false, Telemetry_PowerMonitor_init_default}
#define Telemetry_PowerMonitor_init_default      {0, 0, _PAF_Status_MIN, _PAF_Status_MIN, _PAF_Status_MIN, _PAF_Status_MIN, _PAF_Status_MIN}
#define LightingOnCommand_init_zero              {0, 0}
#define ThrustersControl_init_zero               {_ThrustersState_MIN, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define Telemetry_init_zero                      {0, false, Telemetry_PowerMonitor_init_zero}
#define Telemetry_PowerMonitor_init_zero         {0, 0, _PAF_Status_MIN, _PAF_Status_MIN, _PAF_Status_MIN, _PAF_Status_MIN, _PAF_Status_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define LightingOnCommand_channel_tag            1
#define LightingOnCommand_brightness_tag         2
#define ThrustersControl_state_tag               1
#define ThrustersControl_configuration_tag       2
#define ThrustersControl_level_tag               3
#define Telemetry_PowerMonitor_voltage_tag       1
#define Telemetry_PowerMonitor_current_tag       2
#define Telemetry_PowerMonitor_paf_1_tag         3
#define Telemetry_PowerMonitor_paf_2_tag         4
#define Telemetry_PowerMonitor_paf_3_tag         5
#define Telemetry_PowerMonitor_paf_4_tag         6
#define Telemetry_PowerMonitor_paf_5_tag         7
#define Telemetry_msg_id_tag                     1
#define Telemetry_power_monitor_tag              2

/* Struct field encoding specification for nanopb */
#define LightingOnCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           1) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        2)
#define LightingOnCommand_CALLBACK NULL
#define LightingOnCommand_DEFAULT NULL

#define ThrustersControl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1) \
X(a, STATIC,   SINGULAR, UINT32,   configuration,     2) \
X(a, STATIC,   FIXARRAY, INT32,    level,             3)
#define ThrustersControl_CALLBACK NULL
#define ThrustersControl_DEFAULT NULL

#define Telemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   msg_id,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  power_monitor,     2)
#define Telemetry_CALLBACK NULL
#define Telemetry_DEFAULT NULL
#define Telemetry_power_monitor_MSGTYPE Telemetry_PowerMonitor

#define Telemetry_PowerMonitor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    voltage,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    current,           2) \
X(a, STATIC,   SINGULAR, UENUM,    paf_1,             3) \
X(a, STATIC,   SINGULAR, UENUM,    paf_2,             4) \
X(a, STATIC,   SINGULAR, UENUM,    paf_3,             5) \
X(a, STATIC,   SINGULAR, UENUM,    paf_4,             6) \
X(a, STATIC,   SINGULAR, UENUM,    paf_5,             7)
#define Telemetry_PowerMonitor_CALLBACK NULL
#define Telemetry_PowerMonitor_DEFAULT NULL

extern const pb_msgdesc_t LightingOnCommand_msg;
extern const pb_msgdesc_t ThrustersControl_msg;
extern const pb_msgdesc_t Telemetry_msg;
extern const pb_msgdesc_t Telemetry_PowerMonitor_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define LightingOnCommand_fields &LightingOnCommand_msg
#define ThrustersControl_fields &ThrustersControl_msg
#define Telemetry_fields &Telemetry_msg
#define Telemetry_PowerMonitor_fields &Telemetry_PowerMonitor_msg

/* Maximum encoded size of messages (where known) */
#define DCB_FIRMWARE_LL_PROTOCOL_MESSAGE_PB_H_MAX_SIZE ThrustersControl_size
#define LightingOnCommand_size                   12
#define Telemetry_PowerMonitor_size              20
#define Telemetry_size                           28
#define ThrustersControl_size                    96

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
