/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LightingOnCommand, LightingOnCommand, AUTO)


PB_BIND(ThrustersControl, ThrustersControl, AUTO)


PB_BIND(Telemetry, Telemetry, AUTO)


PB_BIND(Telemetry_PowerMonitor, Telemetry_PowerMonitor, AUTO)







